# kubernetes-fastapi LoadBalancer Service
# Enables the pods in a deployment to be accessible from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: fast-api-svc
  namespace: kube-system
spec:
  selector:
    app: fast-api
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
# kf-api Deployment
# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api
  labels:
    app: fast-api
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-api
  template:
    metadata:
      labels:
        app: fast-api
    spec:
      containers:
        - name: fast-api
          image: 4oh4/kubernetes-fastapi:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          resources:
            # You must specify requests for CPU to autoscale
            # based on CPU utilization
            limits:
              cpu: "100m"
            requests:
              cpu: "100m"
