apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-api
  labels:
    app: hpa-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-api
  template:
    metadata:
      labels:
        app: hpa-api
    spec:
      containers:
        - name: hpa-api
          image: hpa_fastapi:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            # You must specify requests for CPU to autoscale
            # based on CPU utilization
            requests:
              cpu: "250m"
